apiVersion: apps/v1
kind: Deployment
metadata:
  name: zts-sample
  labels:
    app: zts-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zts-sample
  template:
    metadata:
      labels:
        app: zts-sample
    spec:
      containers:
      - name: nginx
        image: zettasetimg/test:zts-acm-application-0.0.2_commitid-3f15cb
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
  imagePullSecrets:
    - name: zts-dockerhub-token
