apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  labels:
    app: nginx-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: zettasetimg/test:zts-acm-application-0.0.2_commitid-42887b
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
