apiVersion: apps/v1
kind: Deployment
metadata:
  name: zts-sample
  labels:
    app: zts-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zts-sample
  template:
    metadata:
      labels:
        app: zts-sample
    spec:
      containers:
      - name: nginx
        image: quay.io/centos7/nginx-120-centos7
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
