---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: default
spec:
  type: GitHub
  pathname: https://github.com/mahesh-zetta/application-samples.git
